#!/bin/bash

if [ $# != 1 ]
then
    echo "Mauvaise syntaxe: ./ArmSimulator nom_du_fichier"
    exit
fi

VAR=$1

if [ ${VAR##*.} = "s" ]
then
    ./Assembleur $VAR
    VAR=`echo ${VAR//.s/.hex}`
fi

./Simulateur $VAR


