#!/bin/bash

if [ $# != 1 ]
then
    echo "Mauvaise syntaxe: ./Simulateur2000 nom_du_fichier"
    exit
fi

VAR=$1

if test ${VAR##*.} = "s"
then
    ./conversion_assembleur_hexa $VAR
    VAR=`echo ${VAR//.s/.hex}`
fi

./simulateur $VAR


